In [1]:
#!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
# demonstration of calculating metrics for a neural network model using sklearn
from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

# TensorFlow e tf.keras
import tensorflow as tf
from tensorflow import keras
import pandas as pd
# Bibliotecas Auxiliares
import seaborn as sns
import numpy as np
import collections
import matplotlib.pyplot as plt
import nest_asyncio
nest_asyncio.apply()
import tensorflow_federated as tff
np.random.seed(0)
from collections import Counter

import collections
import functools
import os
import time
from scipy import stats

from sklearn.model_selection import train_test_split

import datetime;
  
import warnings
warnings.filterwarnings("ignore")

print(tf.__version__)

2023-03-30 17:57:12.100333: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-30 17:57:12.293410: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-30 17:57:12.983563: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/guilherme/cpu-tensorflow-marcelo/nvidia-smi/envs/tf/lib/
2023-03-30 17:57:12.986007: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7';

2.10.0


In [2]:
# y_test     = Array with real values
# yhat_probs = Array with predicted values
def printMetrics(y_test,yhat_probs):
    # predict crisp classes for test set deprecated
    #yhat_classes = model.predict_classes(X_test, verbose=0)
    #yhat_classes = np.argmax(yhat_probs,axis=1)
    yhat_classes = yhat_probs.round()
    # accuracy: (tp + tn) / (p + n)
    accuracy = accuracy_score(y_test, yhat_classes)
    print('Accuracy: %f' % accuracy)
    # precision tp / (tp + fp)
    precision = precision_score(y_test, yhat_classes)
    print('Precision: %f' % precision)
    # recall: tp / (tp + fn)
    recall = recall_score(y_test, yhat_classes)
    print('Recall: %f' % recall)
    # f1: 2 tp / (2 tp + fp + fn)
    f1 = f1_score(y_test, yhat_classes)
    print('F1 score: %f' % f1)
    # kappa
    kappa = cohen_kappa_score(y_test, yhat_classes)
    print('Cohens kappa: %f' % kappa)
    # ROC AUC
    auc = roc_auc_score(y_test, yhat_probs)
    print('ROC AUC: %f' % auc)
    # confusion matrix
    print("\Confusion Matrix")
    matrix = confusion_matrix(y_test, yhat_classes)
    print(matrix)
    
    array = []
    results = dict()
    results['accuracy'] = accuracy
    results['precision'] = precision
    results['recall'] = recall
    results['f1_score'] = f1
    results['cohen_kappa_score'] = kappa
    results['roc_auc_score'] = auc
    results['matrix'] = np.array(matrix,dtype=object)
    results['TP'] = matrix[0][0]
    results['FP'] = matrix[0][1]
    results['FN'] = matrix[1][0]
    results['TN'] = matrix[1][1]
    
    array.append(accuracy)
    array.append(precision)
    array.append(recall)
    array.append(f1)
    array.append(kappa)
    array.append(auc)
    array.append(np.array(matrix,dtype=object))
    array.append(matrix[0][0]) # TP
    array.append(matrix[0][1]) # FP
    array.append(matrix[1][0]) # FN
    array.append(matrix[1][1]) # TN
    
    return results, array

def showGlobalMetrics(metrics):
    accuracy,precision,recall,f1_score,cohen_kappa_score,roc_auc_score = 0,0,0,0,0,0
    for metric in metrics:
        accuracy = accuracy + metric['accuracy']
        precision = precision + metric['precision']
        recall = recall + metric['recall']
        f1_score = f1_score + metric['f1_score']
        cohen_kappa_score = cohen_kappa_score + metric['cohen_kappa_score']
        roc_auc_score = roc_auc_score + metric['roc_auc_score']
        
    # mean
    size = len(metrics)
    print(size)
    accuracy = accuracy / size
    precision = precision / size
    recall = recall / size
    f1_score = f1_score / size
    cohen_kappa_score = cohen_kappa_score / size
    roc_auc_score = roc_auc_score / size
    
    #show:\
    print("accuracy: ",accuracy)
    print("precision: ",precision)
    print("recall: ",recall)
    print("f1_score: ",f1_score)
    print("cohen_kappa_score: ",cohen_kappa_score)
    print("roc_auc_score: ",roc_auc_score)
    
    return [accuracy,precision,recall,f1_score,cohen_kappa_score,roc_auc_score]
    
def create_dataset_time_series_with_one_output(X, y, window_time_steps=1, shift_step=1):
    Xs, ys = [], []
    for i in range(0, len(X) - window_time_steps, shift_step):
        v = X.iloc[i:(i + window_time_steps)].values
        labels = y.iloc[i: i + window_time_steps]
        Xs.append(v)        
        ys.append(stats.mode(labels)[0][0])
        
    if len(y.columns) == 1:
        return np.array(Xs), np.array(ys).reshape(-1, 1)
    else:
        return np.array(Xs), np.array(ys).reshape(-1, len(y.columns))

In [3]:
# configs
EPOCHS = 1
NUM_EPOCHS = EPOCHS
BATCH_SIZE = 32

#TIME_SERIES_SIZE = 4   # Determines the window size. Ex (4,9)
#TIME_STEP_SHIFT  = 1   # Determines specifies the number of steps to move the window forward at each iteration.

baseFolder = "../data_2019_processed/"

# selected features
inputFeatures = ["activity","location","day_of_week",
                 "light","phone_lock","proximity",
                 "sound","time_to_next_alarm", "minutes_day"]
# outputs
outputClasses = ["awake","asleep"]
#outputClasses = ["class"]

In [4]:
# test data comprising 25% of the data. It must be fixed to all models being evaluated
X_test  = pd.read_csv(baseFolder+"test/allData-classification-numeric-normalized.csv")

# input folder
inputFolders = baseFolder

            
dsTrain = ['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
            '0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
            '2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
            '2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
            #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
            '7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
            'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
            'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
            'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
            'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
            'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
            'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', 
            'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
            'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
            'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
            'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
            'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
            'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
            'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
            'PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc', 
            'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
            'rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw', 
            'RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI', 
            'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4', 
            'VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is', 
            'Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw', 
            'XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA', 
            'YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw', 
            'ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM', 
            'ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']


# client datasets used on the training process
dsTrain =  ['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
            '0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
            '2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
            '2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
            #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
            '7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
            'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
            'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
            'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
            'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
            'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
            'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', 
            'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
            'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
            'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
            'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
            'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
            'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
            'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
            #['PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc'], 
            'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
            #['rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw'], 
            #['RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI'], 
            'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4'] 
            #['VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is'], 
            #['Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw'], 
            #['XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA'], 
            #['YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw'], 
            #['ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM'], 
            #['ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']]

In [5]:
# load cliend data
clientList = []

for i in range(0,len(dsTrain)):
    print (i," ", str(inputFolders)+"student_"+dsTrain[i]+"_numeric.csv") #_numeric
    # load client data
    dataset = pd.read_csv(inputFolders+"student_"+dsTrain[i]+"_numeric.csv")
    
    # print(dataset)
    y_train = dataset['class'].copy()
    
    # does not add datasets that dont have instances from both classes
    if y_train.sum() != 0 and (y_train.sum() != len(y_train)):
        clientList.append(dataset)
        
print("Total",(len(clientList)))

0   ../data_2019_processed/student_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs_numeric.csv
1   ../data_2019_processed/student_0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA_numeric.csv
2   ../data_2019_processed/student_2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0_numeric.csv
3   ../data_2019_processed/student_2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys_numeric.csv
4   ../data_2019_processed/student_7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA_numeric.csv
5   ../data_2019_processed/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4_numeric.csv
6   ../data_2019_processed/student_ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc_numeric.csv
7   ../data_2019_processed/student_Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U_numeric.csv
8   ../data_2019_processed/student_CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA_numeric.csv
9   ../data_2019_processed/student_DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc_numeric.csv
10   ../data_2019_processed/student_DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA_numeric.csv
11   ../

In [6]:
# undestand the dataset by looking on their infos
print(X_test.info())

X_test

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136286 entries, 0 to 136285
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   activity            136286 non-null  float64
 1   location            136286 non-null  float64
 2   timestamp           136286 non-null  float64
 3   day_of_week         136286 non-null  float64
 4   light               136286 non-null  float64
 5   phone_lock          136286 non-null  float64
 6   proximity           136286 non-null  float64
 7   sound               136286 non-null  float64
 8   time_to_next_alarm  136286 non-null  float64
 9   minutes_day         136286 non-null  float64
 10  timestamp_text      136286 non-null  object 
 11  class               136286 non-null  object 
dtypes: float64(10), object(2)
memory usage: 12.5+ MB
None


activity  location  timestamp  day_of_week     light  phone_lock  \
0           0.00       1.0   0.000647     1.000000  0.000000         0.0   
1           0.25       1.0   0.000647     1.000000  0.000000         0.0   
2           0.25       1.0   0.000647     1.000000  0.000000         0.0   
3           0.25       1.0   0.000647     1.000000  0.000000         0.0   
4           0.25       1.0   0.000647     1.000000  0.000000         0.0   
...          ...       ...        ...          ...       ...         ...   
136281      0.25       1.0   0.007015     0.166667  0.000056         1.0   
136282      0.25       1.0   0.007015     0.166667  0.000078         1.0   
136283      0.25       1.0   0.007015     0.166667  0.000078         1.0   
136284      0.25       1.0   0.007016     0.166667  0.000085         1.0   
136285      0.50       1.0   0.007016     0.166667  0.000000         1.0   

        proximity     sound  time_to_next_alarm  minutes_day  \
0             1.0  0.655565            0.906151     0.115358   
1             1.0  0.567296            0.906052     0.116053   
2             1.0  0.567296            0.906052     0.116053   
3             1.0  0.660604            0.905952     0.116748   
4             1.0  0.660604            0.905952     0.116748   
...           ...       ...                 ...          ...   
136281        1.0  0.000000            0.000099     0.510076   
136282        1.0  0.000000            0.000694     0.512856   
136283        1.0  0.000000            0.000595     0.513551   
136284        1.0  0.000000            0.000595     0.513551   
136285        0.0  0.000000            0.000496     0.514246   

             timestamp_text   class  
0       2018-05-15 02:46:57  asleep  
1       2018-05-15 02:47:27  asleep  
2       2018-05-15 02:47:57  asleep  
3       2018-05-15 02:48:28  asleep  
4       2018-05-15 02:48:57  asleep  
...                     ...     ...  
136281  2018-06-13 12:14:37   awake  
136282  2018-06-13 12:18:08   awake  
136283  2018-06-13 12:19:08   awake  
136284  2018-06-13 12:19:38   awake  
136285  2018-06-13 12:20:08   awake  

[136286 rows x 12 columns]

In [7]:
# one-hot encoding function
def transform_output_nominal_class_into_one_hot_encoding(dataset):
    # create two classes based on the single class
    one_hot_encoded_data = pd.get_dummies(dataset['class'])
    #print(one_hot_encoded_data)
    dataset['awake'] = one_hot_encoded_data['awake']
    dataset['asleep'] = one_hot_encoded_data['asleep']
    
    return dataset

# one-hot encoding function
def transform_output_numerical_class_into_one_hot_encoding(dataset):
    # create two classes based on the single class
    one_hot_encoded_data = pd.get_dummies(dataset['class'])
    #print(one_hot_encoded_data)
    dataset['awake'] = one_hot_encoded_data[0]
    dataset['asleep'] = one_hot_encoded_data[1]
    
    return dataset

# transform output to one_hot_encoding for the testing dataset
X_test = transform_output_nominal_class_into_one_hot_encoding(X_test)

# transform output to one_hot_encoding for the input dataset
for i in range(0,len(clientList)):
    clientList[i] = transform_output_numerical_class_into_one_hot_encoding(clientList[i])
    #print (clientList[i])

In [8]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136286 entries, 0 to 136285
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   activity            136286 non-null  float64
 1   location            136286 non-null  float64
 2   timestamp           136286 non-null  float64
 3   day_of_week         136286 non-null  float64
 4   light               136286 non-null  float64
 5   phone_lock          136286 non-null  float64
 6   proximity           136286 non-null  float64
 7   sound               136286 non-null  float64
 8   time_to_next_alarm  136286 non-null  float64
 9   minutes_day         136286 non-null  float64
 10  timestamp_text      136286 non-null  object 
 11  class               136286 non-null  object 
 12  awake               136286 non-null  uint8  
 13  asleep              136286 non-null  uint8  
dtypes: float64(10), object(2), uint8(2)
memory usage: 12.7+ MB


In [9]:
def transform_data_type(dataframe):
    
    # transform inputs
    for column in inputFeatures:
        dataframe[column] = dataframe[column].astype('float32')
    
    # transform outputs
    for column in outputClasses:
        dataframe[column] = dataframe[column].astype('float32')
    
    return dataframe

# transforms the data
X_test = transform_data_type(X_test)

X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136286 entries, 0 to 136285
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   activity            136286 non-null  float32
 1   location            136286 non-null  float32
 2   timestamp           136286 non-null  float64
 3   day_of_week         136286 non-null  float32
 4   light               136286 non-null  float32
 5   phone_lock          136286 non-null  float32
 6   proximity           136286 non-null  float32
 7   sound               136286 non-null  float32
 8   time_to_next_alarm  136286 non-null  float32
 9   minutes_day         136286 non-null  float32
 10  timestamp_text      136286 non-null  object 
 11  class               136286 non-null  object 
 12  awake               136286 non-null  float32
 13  asleep              136286 non-null  float32
dtypes: float32(11), float64(1), object(2)
memory usage: 8.8+ MB


In [10]:
# selects the data to train and test
X_test_data = X_test[inputFeatures]
y_test_label = X_test[outputClasses]

# transtorm data to tensor slices
client_test_dataset = tf.data.Dataset.from_tensor_slices((X_test_data.values, y_test_label.values))

#client_test_dataset = client_test_dataset.repeat(NUM_EPOCHS).batch(BATCH_SIZE, drop_remainder=True)
client_test_dataset = client_test_dataset.repeat(NUM_EPOCHS).batch(BATCH_SIZE)

print(client_test_dataset.element_spec)
client_test_dataset

2023-03-30 17:57:16.255691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.


(TensorSpec(shape=(None, 9), dtype=tf.float32, name=None), TensorSpec(shape=(None, 2), dtype=tf.float32, name=None))


2023-03-30 17:57:16.324398: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-03-30 17:57:16.324691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-03-30 17:57:16.327978: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-30 17:57:16.336429: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built witho

<BatchDataset element_spec=(TensorSpec(shape=(None, 9), dtype=tf.float32, name=None), TensorSpec(shape=(None, 2), dtype=tf.float32, name=None))>

In [11]:
federated_training_data = []
# transform the data
for i in range(0,len(clientList)):
    # selects the data to train and test
    data   = clientList[i][inputFeatures]
    labels = clientList[i][outputClasses]
    # transform the data to tensor slices
    client_train_dataset = tf.data.Dataset.from_tensor_slices((data.values, labels.values))
    # apply the configs
    client_train_dataset = client_train_dataset.repeat(NUM_EPOCHS).batch(BATCH_SIZE)
    # transform the data to
    federated_training_data.append(client_train_dataset)

In [12]:
def create_keras_model():
    return tf.keras.models.Sequential([
      tf.keras.layers.InputLayer(input_shape=(9,)),
      #tf.keras.layers.Dense(9, activation=tf.keras.activations.relu), 
      tf.keras.layers.Dense(16, activation=tf.keras.activations.relu),
      tf.keras.layers.Dense(12, activation=tf.keras.activations.relu),
      tf.keras.layers.Dense(2, activation=tf.keras.activations.softmax)
      #tf.keras.layers.Dense(2, activation=tf.nn.sigmoid)
    ])

In [13]:
keras_model = create_keras_model()
#keras_model.summary()
keras_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                160       
                                                                 
 dense_1 (Dense)             (None, 12)                204       
                                                                 
 dense_2 (Dense)             (None, 2)                 26        
                                                                 
Total params: 390
Trainable params: 390
Non-trainable params: 0
_________________________________________________________________


In [14]:
def model_fn():
    # We _must_ create a new model here, and _not_ capture it from an external
    # scope. TFF will call this within different graph contexts.
    #keras_model = create_keras_model()
    keras_model = create_keras_model()
    return tff.learning.from_keras_model(
      keras_model,
      input_spec=client_train_dataset.element_spec,
      loss=tf.keras.losses.CategoricalCrossentropy(), #BinaryCrossentropy
      metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [15]:
fed_avg_process = tff.learning.algorithms.build_weighted_fed_avg(
    model_fn,
    client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),#client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),
    server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0))

In [16]:
print(fed_avg_process.initialize.type_signature.formatted_representation())

( -> <
  global_model_weights=<
    trainable=<
      float32[9,16],
      float32[16],
      float32[16,12],
      float32[12],
      float32[12,2],
      float32[2]
    >,
    non_trainable=<>
  >,
  distributor=<>,
  client_work=<>,
  aggregator=<
    value_sum_process=<>,
    weight_sum_process=<>
  >,
  finalizer=<
    int64
  >
>@SERVER)


In [17]:
state = fed_avg_process.initialize()

In [18]:
roundData = []

columns = ['NN_type','units','epochs','batch_size','max_iterations','Users',
           'round_iteration','start_time','end_time','round_time_s','round_time_m',
           'class','accuracy','precision','recall','f1_score','cohen_kappa_score','roc_auc_score','confusion_matrix',
           'TP','FP','FN','TN']

MAX_ITERATIONS = 120
#NUM_EPOCHS
#BATCH_SIZE
NN_type = 'MLP'
UNITS_NUMBER = 12
USER_NUMBER = len(dsTrain)

generalData = [NN_type,UNITS_NUMBER,NUM_EPOCHS,BATCH_SIZE,MAX_ITERATIONS,USER_NUMBER]

for i in range(0,MAX_ITERATIONS):
    current_time = datetime.datetime.now()
    time_stamp = current_time.timestamp()
    print(i,"Start timestamp:", time_stamp,current_time)
    
    result = fed_avg_process.next(state, federated_training_data[0:19])
    state = result.state
    metrics = result.metrics
    print('round  {}, metrics={}'.format(i,metrics))

    print('')
    #def keras_evaluate(state, round_num):
        # Take our global model weights and push them back into a Keras model to
        # use its standard `.evaluate()` method.
    keras_model = create_keras_model()


    keras_model.compile(
      loss=tf.keras.losses.CategoricalCrossentropy(),
      metrics=[tf.keras.metrics.CategoricalAccuracy()])

    # get neural network weights
    weights = fed_avg_process.get_model_weights(state)
    weights.assign_weights_to(keras_model)


    #tttt.model.assign_weights_to(keras_model)
    yhat_probs = keras_model.predict(X_test_data,verbose=0)

    maxX = yhat_probs.max()
    minX = yhat_probs.min()
    avgX = yhat_probs.mean()

    print(maxX,minX,avgX)
    print(yhat_probs)
    # predict crisp classes for test set deprecated
    #printMetrics(y_test,yhat_probs)
    test = list()

    xx = yhat_probs.round()

    y_test2 = pd.DataFrame(data=xx,columns=['awake','asleep']) 
    y_test_label_label = pd.DataFrame(data=y_test_label,columns=['awake','asleep']) 
    
    # generate time metrics
    current_time2 = datetime.datetime.now()
    time_stamp2 = current_time2.timestamp()
    processing_time_s = (time_stamp2-time_stamp)
    # generate general metrics
    rowData = [i,current_time,current_time2,processing_time_s,(processing_time_s)/60]

    print('')
    print('awake')    
    res,resA = printMetrics(y_test_label_label['awake'],y_test2['awake'])
    test.append(res)
   
    #columns = ['NN_type','units','epochs','batch_size','max_iterations',''Users',
    #            round_iteration','start_time','end_time','round_time_s','round_time_m',
    #           'class','accuracy','precision','recall','f1_score','cohen_kappa_score','roc_auc_score','confusion_matrix',
    #           'TP','FP','FN','TN']
    # new data
    classData = []
    classData = np.concatenate((np.array(['awake'],dtype=object), resA))
    classData = np.concatenate((rowData, classData))
    classData = np.concatenate((generalData, classData))
    roundData.append(classData)
    
    print('')
    print('asleep')
    res,resA = printMetrics(y_test_label_label['asleep'],y_test2['asleep'])
    test.append(res)
    # new data
    classData = np.concatenate((np.array(['asleep'],dtype=object), resA))
    classData = np.concatenate((rowData, classData))
    classData = np.concatenate((generalData, classData))
    roundData.append(classData)
    print('')
    print('Global')
    resA = showGlobalMetrics(test) #return [accuracy,precision,recall,f1_score,cohen_kappa_score,roc_auc_score
    # new data
    classData = np.concatenate((np.array(['avg'],dtype=object), resA))
    classData = np.concatenate((rowData, classData))
    classData = np.concatenate((generalData, classData))
    roundData.append(classData)
    print('')
    print(i,"End timestamp:", time_stamp2,current_time2)
    print('')
    print('')

0 Start timestamp: 1680195440.398579 2023-03-30 17:57:20.398579


2023-03-30 17:57:26.317015: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


round  0, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.81717557), ('loss', 0.4218077), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.91894937 0.081050605 0.5
[[0.85516626 0.14483379]
 [0.8595751  0.14042489]
 [0.8595751  0.14042489]
 ...
 [0.7491856  0.2508144 ]
 [0.7491856  0.2508144 ]
 [0.68774873 0.31225127]]

awake
Accuracy: 0.702192
Precision: 0.702192
Recall: 1.000000
F1 score: 0.825045
Cohens kappa: 0.000000
ROC AUC: 0.500000
\Confusion Matrix
[[    0 40587]
 [    0 95699]]

asleep
Accuracy: 0.702192
Precision: 0.000000
Recall: 0.000000
F1 score: 0.000000
Cohens kappa: 0.000000
ROC AUC: 0.500000
\Confusion Matrix
[[95699     0]
 [40587     0]]

Global
2
accuracy:  0.7021924482338612
precision:  0.3510962241169306
recall:  0.5
f1_score:  0.41252236135957066
cohen_ka

round  7, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.86782706), ('loss', 0.32322964), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9985001 0.0014999227 0.5
[[0.85214525 0.14785478]
 [0.8825403  0.11745976]
 [0.8825403  0.11745976]
 ...
 [0.82710785 0.17289212]
 [0.82710785 0.17289212]
 [0.74514663 0.2548534 ]]

awake
Accuracy: 0.717983
Precision: 0.717228
Recall: 0.987837
F1 score: 0.831059
Cohens kappa: 0.093485
ROC AUC: 0.534769
\Confusion Matrix
[[ 3316 37271]
 [ 1164 94535]]

asleep
Accuracy: 0.717983
Precision: 0.740179
Recall: 0.081701
F1 score: 0.147159
Cohens kappa: 0.093485
ROC AUC: 0.534769
\Confusion Matrix
[[94535  1164]
 [37271  3316]]

Global
2
accuracy:  0.717982771524588
precision:  0.7287034610932518
recall:  0.5347689503885211
f1_score:  0.48910866645

round  14, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8763385), ('loss', 0.30382356), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9995264 0.0004736407 0.5
[[0.814648   0.18535203]
 [0.83806986 0.16193016]
 [0.83806986 0.16193016]
 ...
 [0.8782021  0.12179794]
 [0.8782021  0.12179794]
 [0.837374   0.162626  ]]

awake
Accuracy: 0.718166
Precision: 0.720144
Recall: 0.979143
F1 score: 0.829906
Cohens kappa: 0.108437
ROC AUC: 0.540980
\Confusion Matrix
[[ 4173 36414]
 [ 1996 93703]]

asleep
Accuracy: 0.718166
Precision: 0.676447
Recall: 0.102816
F1 score: 0.178501
Cohens kappa: 0.108437
ROC AUC: 0.540980
\Confusion Matrix
[[93703  1996]
 [36414  4173]]

Global
2
accuracy:  0.7181662092951587
precision:  0.6982954639052965
recall:  0.5409795552094351
f1_score:  0.5042034594

round  21, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8858685), ('loss', 0.2874754), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9995005 0.00049946865 0.5
[[0.782807   0.21719304]
 [0.81308043 0.18691953]
 [0.81308043 0.18691953]
 ...
 [0.8413384  0.15866168]
 [0.8413384  0.15866168]
 [0.8510915  0.14890856]]

awake
Accuracy: 0.710014
Precision: 0.749991
Recall: 0.880563
F1 score: 0.810049
Cohens kappa: 0.213705
ROC AUC: 0.594222
\Confusion Matrix
[[12496 28091]
 [11430 84269]]

asleep
Accuracy: 0.710014
Precision: 0.522277
Recall: 0.307882
F1 score: 0.387395
Cohens kappa: 0.213705
ROC AUC: 0.594222
\Confusion Matrix
[[84269 11430]
 [28091 12496]]

Global
2
accuracy:  0.7100142347709962
precision:  0.6361340604248884
recall:  0.5942224246861607
f1_score:  0.5987219306

round  28, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.88080287), ('loss', 0.2889597), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99896467 0.0010352969 0.5
[[0.8606271  0.1393729 ]
 [0.8817106  0.11828934]
 [0.8817106  0.11828934]
 ...
 [0.8703939  0.12960614]
 [0.8703939  0.12960614]
 [0.8896379  0.11036211]]

awake
Accuracy: 0.706470
Precision: 0.728185
Recall: 0.928609
F1 score: 0.816275
Cohens kappa: 0.136883
ROC AUC: 0.555652
\Confusion Matrix
[[ 7415 33172]
 [ 6832 88867]]

asleep
Accuracy: 0.706470
Precision: 0.520460
Recall: 0.182694
F1 score: 0.270453
Cohens kappa: 0.136883
ROC AUC: 0.555652
\Confusion Matrix
[[88867  6832]
 [33172  7415]]

Global
2
accuracy:  0.7064702170435702
precision:  0.6243228500345006
recall:  0.5556517302001626
f1_score:  0.543363622

round  35, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.88087404), ('loss', 0.29483524), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9993837 0.00061632186 0.5
[[0.8479018  0.15209822]
 [0.8730212  0.12697886]
 [0.8730212  0.12697886]
 ...
 [0.9197051  0.08029488]
 [0.9197051  0.08029488]
 [0.9487532  0.05124687]]

awake
Accuracy: 0.717249
Precision: 0.735073
Recall: 0.933928
F1 score: 0.822654
Cohens kappa: 0.171836
ROC AUC: 0.570138
\Confusion Matrix
[[ 8375 32212]
 [ 6323 89376]]

asleep
Accuracy: 0.717249
Precision: 0.569805
Recall: 0.206347
F1 score: 0.302975
Cohens kappa: 0.171836
ROC AUC: 0.570138
\Confusion Matrix
[[89376  6323]
 [32212  8375]]

Global
2
accuracy:  0.7172490204423052
precision:  0.6524389778780557
recall:  0.5701375570228493
f1_score:  0.56281469

round  42, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8828767), ('loss', 0.2879963), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9996915 0.00030848803 0.5
[[0.7916381  0.2083619 ]
 [0.79672277 0.20327719]
 [0.79672277 0.20327719]
 ...
 [0.8826262  0.1173738 ]
 [0.8826262  0.1173738 ]
 [0.9404828  0.05951723]]

awake
Accuracy: 0.726692
Precision: 0.731759
Recall: 0.964242
F1 score: 0.832066
Cohens kappa: 0.166802
ROC AUC: 0.565411
\Confusion Matrix
[[ 6761 33826]
 [ 3422 92277]]

asleep
Accuracy: 0.726692
Precision: 0.663950
Recall: 0.166580
F1 score: 0.266338
Cohens kappa: 0.166802
ROC AUC: 0.565411
\Confusion Matrix
[[92277  3422]
 [33826  6761]]

Global
2
accuracy:  0.7266923968712854
precision:  0.6978543395340149
recall:  0.5654112413771101
f1_score:  0.5492024132

round  49, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.88942474), ('loss', 0.28031358), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.999747 0.00025306395 0.5
[[0.89768195 0.10231806]
 [0.9080509  0.0919491 ]
 [0.9080509  0.0919491 ]
 ...
 [0.8734796  0.12652045]
 [0.8734796  0.12652045]
 [0.91781664 0.08218335]]

awake
Accuracy: 0.726979
Precision: 0.726467
Recall: 0.980292
F1 score: 0.834505
Cohens kappa: 0.144195
ROC AUC: 0.554995
\Confusion Matrix
[[ 5264 35323]
 [ 1886 93813]]

asleep
Accuracy: 0.726979
Precision: 0.736224
Recall: 0.129697
F1 score: 0.220542
Cohens kappa: 0.144195
ROC AUC: 0.554995
\Confusion Matrix
[[93813  1886]
 [35323  5264]]

Global
2
accuracy:  0.7269785597933757
precision:  0.7313452235102278
recall:  0.5549945379825134
f1_score:  0.527523511

round  56, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8965004), ('loss', 0.27088964), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9996258 0.00037418547 0.5
[[0.92549926 0.07450075]
 [0.9371833  0.06281672]
 [0.9371833  0.06281672]
 ...
 [0.75796425 0.24203576]
 [0.75796425 0.24203576]
 [0.7842982  0.2157018 ]]

awake
Accuracy: 0.719340
Precision: 0.727102
Recall: 0.960992
F1 score: 0.827844
Cohens kappa: 0.141437
ROC AUC: 0.555274
\Confusion Matrix
[[ 6070 34517]
 [ 3733 91966]]

asleep
Accuracy: 0.719340
Precision: 0.619198
Recall: 0.149555
F1 score: 0.240921
Cohens kappa: 0.141437
ROC AUC: 0.555274
\Confusion Matrix
[[91966  3733]
 [34517  6070]]

Global
2
accuracy:  0.7193402110268112
precision:  0.6731499352338755
recall:  0.555273777095623
f1_score:  0.5343823286

round  63, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8961667), ('loss', 0.26683325), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99961627 0.00038373712 0.5
[[0.8874783  0.11252166]
 [0.9038745  0.09612549]
 [0.9038745  0.09612549]
 ...
 [0.59616375 0.4038363 ]
 [0.59616375 0.4038363 ]
 [0.5807148  0.41928515]]

awake
Accuracy: 0.716324
Precision: 0.736704
Recall: 0.927502
F1 score: 0.821165
Cohens kappa: 0.177024
ROC AUC: 0.572948
\Confusion Matrix
[[ 8864 31723]
 [ 6938 88761]]

asleep
Accuracy: 0.716324
Precision: 0.560942
Recall: 0.218395
F1 score: 0.314388
Cohens kappa: 0.177024
ROC AUC: 0.572948
\Confusion Matrix
[[88761  6938]
 [31723  8864]]

Global
2
accuracy:  0.7163244940786287
precision:  0.6488226408264542
recall:  0.5729484536884362
f1_score:  0.56777647

round  70, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.89620346), ('loss', 0.26001564), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9998 0.0001999454 0.5
[[0.895092   0.10490795]
 [0.90362555 0.09637443]
 [0.90362555 0.09637443]
 ...
 [0.6724143  0.3275857 ]
 [0.6724143  0.3275857 ]
 [0.6590424  0.34095755]]

awake
Accuracy: 0.719524
Precision: 0.734114
Recall: 0.941609
F1 score: 0.825015
Cohens kappa: 0.170132
ROC AUC: 0.568742
\Confusion Matrix
[[ 7950 32637]
 [ 5588 90111]]

asleep
Accuracy: 0.719524
Precision: 0.587236
Recall: 0.195876
F1 score: 0.293764
Cohens kappa: 0.170132
ROC AUC: 0.568742
\Confusion Matrix
[[90111  5588]
 [32637  7950]]

Global
2
accuracy:  0.719523648797382
precision:  0.660674861306167
recall:  0.5687420559490689
f1_score:  0.55938959874328

round  77, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8976245), ('loss', 0.26109594), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99975187 0.00024810847 0.5
[[0.93652856 0.06347139]
 [0.9427458  0.05725419]
 [0.9427458  0.05725419]
 ...
 [0.50017464 0.4998254 ]
 [0.50017464 0.4998254 ]
 [0.52265877 0.47734126]]

awake
Accuracy: 0.709823
Precision: 0.723717
Recall: 0.949069
F1 score: 0.821214
Cohens kappa: 0.120191
ROC AUC: 0.547391
\Confusion Matrix
[[ 5914 34673]
 [ 4874 90825]]

asleep
Accuracy: 0.709823
Precision: 0.548202
Recall: 0.145712
F1 score: 0.230229
Cohens kappa: 0.120191
ROC AUC: 0.547391
\Confusion Matrix
[[90825  4874]
 [34673  5914]]

Global
2
accuracy:  0.7098234594896028
precision:  0.6359592091078738
recall:  0.5473905796700549
f1_score:  0.52572118

round  84, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8966698), ('loss', 0.26251763), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99975926 0.0002407528 0.5
[[0.9085698  0.09143017]
 [0.9155708  0.08442914]
 [0.9155708  0.08442914]
 ...
 [0.6222302  0.37776983]
 [0.6222302  0.37776983]
 [0.6813406  0.31865945]]

awake
Accuracy: 0.710814
Precision: 0.729516
Recall: 0.934743
F1 score: 0.819476
Cohens kappa: 0.145315
ROC AUC: 0.558780
\Confusion Matrix
[[ 7420 33167]
 [ 6245 89454]]

asleep
Accuracy: 0.710814
Precision: 0.542993
Recall: 0.182817
F1 score: 0.273538
Cohens kappa: 0.145315
ROC AUC: 0.558780
\Confusion Matrix
[[89454  6245]
 [33167  7420]]

Global
2
accuracy:  0.7108140234506846
precision:  0.6362545996629961
recall:  0.5587802339779093
f1_score:  0.546507150

round  91, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8872846), ('loss', 0.27269953), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99989545 0.00010458855 0.5
[[0.87596    0.12404004]
 [0.88466805 0.11533201]
 [0.88466805 0.11533201]
 ...
 [0.80354995 0.19645004]
 [0.80354995 0.19645004]
 [0.85770667 0.14229338]]

awake
Accuracy: 0.723508
Precision: 0.731507
Recall: 0.957795
F1 score: 0.829495
Cohens kappa: 0.163150
ROC AUC: 0.564442
\Confusion Matrix
[[ 6944 33643]
 [ 4039 91660]]

asleep
Accuracy: 0.723508
Precision: 0.632250
Recall: 0.171089
F1 score: 0.269304
Cohens kappa: 0.163150
ROC AUC: 0.564442
\Confusion Matrix
[[91660  4039]
 [33643  6944]]

Global
2
accuracy:  0.7235079171741778
precision:  0.6818783340565515
recall:  0.5644420086659324
f1_score:  0.54939930

round  98, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8834044), ('loss', 0.27403575), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9998872 0.00011271943 0.5
[[0.8467819  0.15321809]
 [0.85534054 0.14465946]
 [0.85534054 0.14465946]
 ...
 [0.71001107 0.28998896]
 [0.71001107 0.28998896]
 [0.81617534 0.18382458]]

awake
Accuracy: 0.718394
Precision: 0.730020
Recall: 0.950470
F1 score: 0.825785
Cohens kappa: 0.153033
ROC AUC: 0.560829
\Confusion Matrix
[[ 6948 33639]
 [ 4740 90959]]

asleep
Accuracy: 0.718394
Precision: 0.594456
Recall: 0.171188
F1 score: 0.265825
Cohens kappa: 0.153033
ROC AUC: 0.560829
\Confusion Matrix
[[90959  4740]
 [33639  6948]]

Global
2
accuracy:  0.7183936721306664
precision:  0.6622377978255688
recall:  0.560828760318732
f1_score:  0.5458050770

round  105, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.8956856), ('loss', 0.25915542), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99951184 0.00048817857 0.5
[[0.902851   0.09714901]
 [0.92200327 0.07799675]
 [0.92200327 0.07799675]
 ...
 [0.56100565 0.43899435]
 [0.56100565 0.43899435]
 [0.6958461  0.30415395]]

awake
Accuracy: 0.716229
Precision: 0.734700
Recall: 0.932664
F1 score: 0.821930
Cohens kappa: 0.169592
ROC AUC: 0.569284
\Confusion Matrix
[[ 8357 32230]
 [ 6444 89255]]

asleep
Accuracy: 0.716229
Precision: 0.564624
Recall: 0.205903
F1 score: 0.301762
Cohens kappa: 0.169592
ROC AUC: 0.569284
\Confusion Matrix
[[89255  6444]
 [32230  8357]]

Global
2
accuracy:  0.716229106437932
precision:  0.6496618845313779
recall:  0.5692836206296195
f1_score:  0.56184595

round  112, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.89754105), ('loss', 0.26434883), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.99953365 0.00046638594 0.5
[[0.81346864 0.18653141]
 [0.8594773  0.1405227 ]
 [0.8594773  0.1405227 ]
 ...
 [0.5618449  0.43815508]
 [0.5618449  0.43815508]
 [0.62032795 0.37967208]]

awake
Accuracy: 0.730823
Precision: 0.754397
Recall: 0.914336
F1 score: 0.826702
Cohens kappa: 0.248184
ROC AUC: 0.606230
\Confusion Matrix
[[12100 28487]
 [ 8198 87501]]

asleep
Accuracy: 0.730823
Precision: 0.596118
Recall: 0.298125
F1 score: 0.397471
Cohens kappa: 0.248184
ROC AUC: 0.606230
\Confusion Matrix
[[87501  8198]
 [28487 12100]]

Global
2
accuracy:  0.7308234154645378
precision:  0.675257425354731
recall:  0.6062302941967563
f1_score:  0.6120861

round  119, metrics=OrderedDict([('distributor', ()), ('client_work', OrderedDict([('train', OrderedDict([('categorical_accuracy', 0.9083939), ('loss', 0.24766172), ('num_examples', 407451), ('num_batches', 12745)]))])), ('aggregator', OrderedDict([('mean_value', ()), ('mean_weight', ())])), ('finalizer', OrderedDict([('update_non_finite', 0)]))])

0.9995702 0.0004298259 0.5
[[0.8338342  0.16616578]
 [0.8649584  0.13504158]
 [0.8649584  0.13504158]
 ...
 [0.5793995  0.42060044]
 [0.5793995  0.42060044]
 [0.6576879  0.3423121 ]]

awake
Accuracy: 0.728842
Precision: 0.758288
Recall: 0.901065
F1 score: 0.823534
Cohens kappa: 0.256635
ROC AUC: 0.611914
\Confusion Matrix
[[13100 27487]
 [ 9468 86231]]

asleep
Accuracy: 0.728842
Precision: 0.580468
Recall: 0.322763
F1 score: 0.414852
Cohens kappa: 0.256635
ROC AUC: 0.611914
\Confusion Matrix
[[86231  9468]
 [27487 13100]]

Global
2
accuracy:  0.7288422875423741
precision:  0.6693779825227226
recall:  0.61191412166953
f1_score:  0.61919312671

In [19]:
dataMetrics = pd.DataFrame(data=roundData,columns=columns) 

dataMetrics

NN_type units epochs batch_size max_iterations Users  round_iteration  \
0       MLP    12      1         32            120    20                0   
1       MLP    12      1         32            120    20                0   
2       MLP    12      1         32            120    20                0   
3       MLP    12      1         32            120    20                1   
4       MLP    12      1         32            120    20                1   
..      ...   ...    ...        ...            ...   ...              ...   
355     MLP    12      1         32            120    20              118   
356     MLP    12      1         32            120    20              118   
357     MLP    12      1         32            120    20              119   
358     MLP    12      1         32            120    20              119   
359     MLP    12      1         32            120    20              119   

                    start_time                   end_time  round_time_s  ...  \
0   2023-03-30 17:57:20.398579 2023-03-30 17:58:57.670137     97.271558  ...   
1   2023-03-30 17:57:20.398579 2023-03-30 17:58:57.670137     97.271558  ...   
2   2023-03-30 17:57:20.398579 2023-03-30 17:58:57.670137     97.271558  ...   
3   2023-03-30 17:58:58.130017 2023-03-30 18:00:13.137874     75.007857  ...   
4   2023-03-30 17:58:58.130017 2023-03-30 18:00:13.137874     75.007857  ...   
..                         ...                        ...           ...  ...   
355 2023-03-30 20:31:28.976822 2023-03-30 20:32:42.572585     73.595763  ...   
356 2023-03-30 20:31:28.976822 2023-03-30 20:32:42.572585     73.595763  ...   
357 2023-03-30 20:32:43.032854 2023-03-30 20:33:55.560652     72.527798  ...   
358 2023-03-30 20:32:43.032854 2023-03-30 20:33:55.560652     72.527798  ...   
359 2023-03-30 20:32:43.032854 2023-03-30 20:33:55.560652     72.527798  ...   

     precision    recall  f1_score  cohen_kappa_score  roc_auc_score  \
0     0.702192  1.000000  0.825045           0.000000       0.500000   
1     0.000000  0.000000  0.000000           0.000000       0.500000   
2     0.351096  0.500000  0.412522           0.000000       0.500000   
3     0.702192  1.000000  0.825045           0.000000       0.500000   
4     0.000000  0.000000  0.000000           0.000000       0.500000   
..         ...       ...       ...                ...            ...   
355   0.519601  0.429768  0.470434           0.274937       0.630625   
356   0.647140  0.630625  0.636255           0.274937       0.630625   
357   0.758288  0.901065  0.823534           0.256635       0.611914   
358   0.580468  0.322763  0.414852           0.256635       0.611914   
359   0.669378  0.611914  0.619193           0.256635       0.611914   

                     confusion_matrix       TP       FP       FN       TN  
0            [[0, 40587], [0, 95699]]      0.0  40587.0      0.0  95699.0  
1            [[95699, 0], [40587, 0]]  95699.0      0.0  40587.0      0.0  
2                                None      NaN      NaN      NaN      NaN  
3            [[0, 40587], [0, 95699]]      0.0  40587.0      0.0  95699.0  
4            [[95699, 0], [40587, 0]]  95699.0      0.0  40587.0      0.0  
..                                ...      ...      ...      ...      ...  
355  [[79572, 16127], [23144, 17443]]  79572.0  16127.0  23144.0  17443.0  
356                              None      NaN      NaN      NaN      NaN  
357   [[13100, 27487], [9468, 86231]]  13100.0  27487.0   9468.0  86231.0  
358   [[86231, 9468], [27487, 13100]]  86231.0   9468.0  27487.0  13100.0  
359                              None      NaN      NaN      NaN      NaN  

[360 rows x 23 columns]

In [20]:
dataMetrics.to_csv("result1epochsMLPunbalanced2.csv", sep=',', encoding='utf-8', index=False)

In [21]:
metrics = ['class',"epochs","accuracy","precision","recall","f1_score"]
#dfMetricsClass = dsMetrics.loc[dsMetrics['class'] == "asleep"]
ss = dataMetrics.loc[dataMetrics['class'] == "avg"]

ss.loc[ss['accuracy'] == ss['accuracy'].max()][metrics]

class epochs  accuracy  precision    recall  f1_score
344   avg      1  0.737853   0.683225  0.631803  0.641848

In [22]:
ss.loc[ss['recall'] == ss['recall'].max()][metrics]

class epochs  accuracy  precision    recall  f1_score
344   avg      1  0.737853   0.683225  0.631803  0.641848

In [26]:
ss.loc[ss['recall'] == ss['recall'].max()][metrics]

class epochs  accuracy  precision    recall  f1_score
344   avg      1  0.737853   0.683225  0.631803  0.641848

In [24]:
cc = dataMetrics.loc[dataMetrics['class'] == "asleep"]
cc.loc[ss['recall'] == cc['recall'].max()][metrics]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [25]:
dsMetrics.iloc[340:345][metrics]

NameError: name 'dsMetrics' is not defined